### PR TITLE
Translation into Latin Spanish rev1

### PR DESCRIPTION
**Pull request by RockLee-BC**

### CODE REVIEW

**Comment by DiegoAndresCortes** [comment]
Vas a poner PR por cada 1 o vas a ir agregando en este?

**Comment by RockLee-BC** [comment]
Voy a ir agregando a este para no hacerme un lio yo, ahora ire haciendo todos y cuando termine hago todos!

**Comment by dragomano** [comment]
Can you merge all your translations into one PR?

**Comment by DiegoAndresCortes** [comment]
I think this PR is a draft he wants to translate all the addons

**Comment by RockLee-BC** [comment]
It is a draft in itself and in order not to get lost in the translation, I cannot understand this everything yet a git :P

**Comment by RockLee-BC** [comment]
They are already and add the translation es ... anything comments to me

**Pull request closed without merging**
