### PR TITLE
Add spanish.txt

### PR DESCRIPTION
**Pull request by RockLee-BC**

### CODE REVIEW

**Comment by dragomano** [comment]
Did you test this for both languages - spanish_es and spanish_latin?

**Comment by RockLee-BC** [comment]
Yes, it must be valid for both, so generate Spanish, should I create one for Latin and another for es?

**Comment by dragomano** [comment]
You can use one readme, but you need to test after that, for each language.
`<readme parsebbc="true" lang="spanish_es" type="file">readme/spanish.txt</readme>`
`<readme parsebbc="true" lang="spanish_latin" type="file">readme/spanish.txt</readme>`

**Comment by RockLee-BC** [comment]
Ah perfect then I change it, because I used something neutral. It has to be valid for both.

**Pull request merged**
